export const locators = {
    PracticeForm: ".accordion .element-group:nth-child(2) #item-0",
    FirstName: "#firstName",
    LastName: "#lastName",
    Email: "#userEmail",
    GenderMale: "#genterWrapper>div:nth-child(2)>div:nth-child(1)",
    GenderFemale: "#genterWrapper>div:nth-child(2)>div:nth-child(2) label",
    GenderOther: "#genterWrapper>div:nth-child(2)>div:nth-child(3) label",
    Mobile: "#userNumber",
    DateBirth: "#dateOfBirthInput",
    Subjects: "#subjectsContainer input",
    HobbiesSports: "#hobbiesWrapper>div:nth-child(2)>div:nth-child(1) label",
    HobbiesReading: "#hobbiesWrapper>div:nth-child(2)>div:nth-child(2) label",
    HobbiesMusic: "#hobbiesWrapper>div:nth-child(2)>div:nth-child(3) label",
    Picture: "#uploadPicture",
    CurrentAddress: "#currentAddress",
    State: "#state svg",
    StateOptions: "#state >div:nth-child(3)>div>div",
    City: "#city svg",
    CityOptions: "#react-select-4-option-0",
    Submit: "#submit",
    Modal: "#example-modal-sizes-title-lg",
    StudentFullName: "[class='table-responsive']>table>tbody>tr:nth-child(1)>td:nth-child(2)",
    StudentEmail: "[class='table-responsive']>table>tbody>tr:nth-child(2)>td:nth-child(2)",
    StudentGender: "[class='table-responsive']>table>tbody>tr:nth-child(3)>td:nth-child(2)",
    StudentMobile: "[class='table-responsive']>table>tbody>tr:nth-child(4)>td:nth-child(2)",
    StudentDateOfBirth: "[class='table-responsive']>table>tbody>tr:nth-child(5)>td:nth-child(2)",
    StudentSubject: "[class='table-responsive']>table>tbody>tr:nth-child(6)>td:nth-child(2)",
    StudentHobbies: "[class='table-responsive']>table>tbody>tr:nth-child(7)>td:nth-child(2)",
    StudentPicture: "[class='table-responsive']>table>tbody>tr:nth-child(8)>td:nth-child(2)",
    StudentAddress: "[class='table-responsive']>table>tbody>tr:nth-child(9)>td:nth-child(2)",
    StudentStateNCity: "[class='table-responsive']>table>tbody>tr:nth-child(10)>td:nth-child(2)"
}