export const locators = {
    WebTables: "[class='accordion']>[class='element-group']:nth-child(1) #item-3",
    WebTablesAdd: "#addNewRecordButton",
    BrokenLinksImages: "[class='element-list collapse show'] #item-6",
    BrokenImage: "[class='col-12 mt-4 col-md-6']>div:nth-child(2)>img:nth-child(6)",
    FirstNameInput: "#firstName",
    LastNameInput: "#lastName",
    EmailInput: "#userEmail",
    AgeInput: "#age",
    SalaryInput: "#salary",
    DepartmentInput: "#department",
    SearchInput: "#searchBox",
    Rows: "#rt-tr-group",
    Submit: "#submit",
    Modal: "#registration-form-modal",
    Edit: "#edit-record-2",
    FindFirstName: "[class='rt-tbody']>div:nth-child(1)>div>div:nth-child(1)",
    FindLastName: "[class='rt-tbody']>div:nth-child(1)>div>div:nth-child(2)",
    FindAge: "[class='rt-tbody']>div:nth-child(1)>div>div:nth-child(3)",
    FindEmail: "[class='rt-tbody']>div:nth-child(row)>div>div:nth-child(4)",
    FindSalary: "[class='rt-tbody']>div:nth-child(1)>div>div:nth-child(5)",
    FindDepartment: "[class='rt-tbody']>div:nth-child(1)>div>div:nth-child(6)",
}